sudo: false
language: 
  - go
go:
  - 1.8.3

before_install:
- export PATH=/home/travis/gopath/bin:$PATH

install:
- go get -v github.com/golang/lint/golint
- go get github.com/wangduotj/gmsm

script:
- go test 

notifications:
  email: false
