sudo: false
language: 
  - go
go:
  - 1.8.3

install:
  - go get -v github.com/golang/lint/golint
  - go get -d -t -v github.com/wangduotj/wangduotj
  - go build -v ./...

script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...


notifications:
  email: false
